from tkinter import*
window=Tk()
window.title('Simple Intrest Calculator app')
window.geometry('400x400')
frame=Frame(master=window,height=200,width=360,bg="#d0efff")
lbl1=Label(frame,text="Principal",bg="#3895D3",fg='white',width=12)
lbl2=Label(frame,text="Rate of Intrest",bg="#3895D3",fg='white',width=12)
lbl3=Label(frame,text="Number of years",bg="#3895D3",fg='white',width=12)
p_entry=Entry(frame)
r_entry=Entry(frame)
n_entry=Entry(frame)
def display():
    P = float(p_entry.get())
    R = float(r_entry.get())
    T = float(n_entry.get())
    SI = (P * R * T) / 100
    result_label.config(text=f"Simple Interest: {SI:.2f}")
btn=Button(text="Check The Interest",command=display,bg="red")
frame.place(x=20,y=20)
lbl1.place(x=20,y=20)
p_entry.place(x=150,y=20)
lbl2.place(x=20,y=80)
r_entry.place(x=150,y=80)
lbl3.place(x=20,y=140)
n_entry.place(x=150,y=140)
btn.place(x=130,y=210)
result_label = Label(window, text="Simple Interest: ")
result_label.pack()
window.mainloop()